### ISSUE TITLE
FPS when following a citizen/vehicle

### ISSUE THREAD

**Issue by johanneseckert** [AlexanderDzhoganov/Skylines-FPSCamera#1]
(Haven't tried the mod yet, but will do tonight!)

Is it possible to attach to a citizen/vehicle/bus/seagull first, then entering FPS view and so following through the city through the person's eyes, exactly?

**Comment by AlexanderDzhoganov** [comment]
No, sorry, at the moment it's only a first-person camera with no extra features. Definitely look forward to this and even cooler stuff in the next versions :)

**Comment by johanneseckert** [comment]
thanks for this awesome mod!
you could leave this issue open and track features with it :-)

**Comment by AlexanderDzhoganov** [comment]
Sure

**Comment by AlexanderDzhoganov** [comment]
This has been implemented :)
