### ISSUE TITLE
Keyboard localization

### ISSUE THREAD

**Issue by Outpox** [AlexanderDzhoganov/Skylines-FPSCamera#2]
Hey there,
Wouldn't it be possible to use the key set in the game parameters instead of it beeing hard coded ?
I'm on an azerty keyboard, which is why I'm asking :p

**Comment by AlexanderDzhoganov** [comment]
Sure, it should be a pretty easy change. PRs are welcome, if not I will fix this sometime in the future.

**Comment by Outpox** [comment]
I'd like to do it, unfortunatly I'm not that much a C# dev, and haven't done much with Unity.
If you've got some hints I'd gladly help tough. I gave a look at the C:S wiki but didn't find anything on how to retrieve the settings.

**Comment by AlexanderDzhoganov** [comment]
Fixed in the latest version, the mod now uses whatever has been setup in the game's Settings.
