### ISSUE TITLE
Install manually

### ISSUE THREAD

**Issue by jackfood** [AlexanderDzhoganov/Skylines-FPSCamera#3]
Is it possible to install your mod manually into C:S?

**Comment by SurelyExploding** [comment]
You could download Visual Studio Community 2013 and compile the code yourself. Honestly I'm kind of against giving advantages to people who haven't purchased the game, but I'll put a download up on an external site when I get home.

**Comment by topSurely** [comment]
You could get Visual Studio Community 2013 and build the code yourself.

Also sorry about my last reply, I thought this issue was on my fork.

**Comment by AlexanderDzhoganov** [comment]
I don't support pirated copies of the game.
